version: "3.8"

services:
  app:
    image: first022/counter:v1
    container_name: counter_app
    restart: always
    ports:
      - "3000:3000" 
    environment:
      - MONGODB_URI=${MONGODB_URI}
  
