version: "3.8"

services:
  app:
    image: first022/counter:v1
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "${WWW_PORT}:3000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: s6530613022
      MONGO_INITDB_ROOT_PASSWORD: uJwKXJVX3KH3uwA0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
